/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEmailTemplatesRouteImport } from './routes/_authenticated/email-templates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailTemplatesRoute =
  AuthenticatedEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/analytics'
    | '/crm'
    | '/dashboard'
    | '/email-templates'
    | '/profile'
    | '/saved'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/analytics'
    | '/crm'
    | '/dashboard'
    | '/email-templates'
    | '/profile'
    | '/saved'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/analytics'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-templates'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/_authenticated/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-templates': {
      id: '/_authenticated/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailTemplatesRoute: typeof AuthenticatedEmailTemplatesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailTemplatesRoute: AuthenticatedEmailTemplatesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
